  try {
  } catch (org.example.whateverError) {
  } catch (org.example.whateverError local.foo) {
  }